version = 0.1

[default.deploy]
stack_name = "posterite-mvp"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
s3_prefix = "posterit-e-mvp"
image_repositories = []

[default.deploy.parameters]
stack_name = "posterit-e-core"
resolve_s3 = true
s3_prefix = "posterit-e-core"
region = "us-east-2"
profile = "personal"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
